export type TypographyStyle = "bold_condensed" | "kinetic_display" | "editorial_serif" | "clean_sans" | "mono_typewriter" | "minimal_modern";
export type BackgroundStyle = "dark_neutral" | "light_clean" | "paper_texture" | "gradient_editorial" | "solid_accent";
export type TextureStyle = "halftone" | "paper_grain" | "newspaper" | "dust_scratches" | "clean";
export type PhotoStyle = "polaroid" | "newspaper_cutout" | "paper_card" | "clean_frame" | "duotone";
export type TransitionStyleType = "whip" | "paper_tear" | "punch_cut" | "flash" | "seamless_slide" | "none";
export type MotionStyleType = "kinetic" | "micro_float" | "smooth_drift" | "parallax" | "snappy_pop" | "static";

export interface VisualStyleDNA {
  id: string;
  name: string;
  description: string;
  
  // Density & Pacing
  visualDensity: number; // 0.00 (clean) to 1.00 (intense editorial)
  pacingVisual: "fast_dynamic" | "editorial_rhythmic" | "balanced" | "calm_spacious";
  
  // Typography
  typographyStyle: TypographyStyle;
  typographyWeight: "bold" | "black" | "heavy" | "medium";
  typographyScale: number; // e.g. 1.25
  captionVisualStyle: "kinetic_highlight" | "editorial_box" | "minimal_clean" | "bold_condensed";
  
  // Colors & Aesthetic
  accentColor: string; // e.g. "#E11D48" or "#F59E0B"
  backgroundStyle: BackgroundStyle;
  textureStyle: TextureStyle;
  colorMood: "dark_editorial" | "vibrant_pop" | "monochrome_newspaper" | "cinematic_warm" | "clean_light";
  
  // Collage & Paper Elements
  collageIntensity: number; // 0.0 to 1.0
  photoStyle: PhotoStyle;
  paperStyle: "torn_rough" | "straight_card" | "wrinkled" | "none";
  newspaperStyle: "vintage_article" | "bold_headline" | "classifieds" | "none";
  polaroidStyle: "vintage_white" | "black_border" | "shadowed" | "none";
  halftoneIntensity: number; // 0.0 to 1.0
  cutoutStyle: "subject_isolate" | "paper_edge" | "sticker_border" | "none";
  shadowStyle: "layered_drop" | "hard_offset" | "soft_ambient" | "none";
  borderStyle: "paper_deckle" | "solid_2px" | "dashed" | "none";
  
  // Motion & Camera
  transitionStyle: TransitionStyleType;
  motionIntensity: number; // 0.0 to 1.0
  zoomIntensity: number; // 1.05 to 1.35
  punchInFrequency: number; // 0.0 to 1.0
  brollFrequency: number; // 0.0 to 1.0
  talkingHeadRatio: number; // 0.0 to 1.0
  supportingVisualRatio: number; // 0.0 to 1.0
  graphicRatio: number; // 0.0 to 1.0
  
  // Diagram / Map / Screenshots / Icons
  diagramUsage: "frequent" | "selective" | "rare" | "none";
  mapUsage: "frequent" | "selective" | "rare" | "none";
  screenshotUsage: "frequent" | "selective" | "rare" | "none";
  iconUsage: "frequent" | "selective" | "rare" | "none";
  
  // Micro motion & Hierarchy
  microMotion: "subtle_drift" | "floating_parallax" | "breathe" | "static" | "snappy_pop" | "smooth_drift";
  compositionStyle: "layered_collage" | "centered_focus" | "rule_of_thirds" | "split_screen";
  visualHierarchy: "bold_primary_secondary" | "equal_weight" | "minimalist_focus";
  negativeSpace: "generous" | "balanced" | "dense";
  
  // Metadata
  source: "DEFAULT" | "USER" | "LEARNED" | "STYLE_PRESET" | "REFERENCE";
  confidence: number;
  evidence: string;
  version: number;
  projectId?: string;
}

export type StylePresetId = 
  | "OMNISTRIH_EDITORIAL"
  | "AI_KREATIVNY_EDITOR"
  | "CINEMATIC"
  | "CLEAN_PROFESSIONAL"
  | "SOCIAL_FAST"
  | "DOCUMENTARY"
  | "EDUCATIONAL"
  | "PODCAST"
  | "NEWS_EDITORIAL"
  | "MINIMAL"
  | "CUSTOM";

export const STYLE_PRESETS: Record<StylePresetId, VisualStyleDNA> = {
  OMNISTRIH_EDITORIAL: {
    id: "OMNISTRIH_EDITORIAL",
    name: "OmniStrih Editorial",
    description: "High-impact editorial design with kinetic typography, paper cutouts, polaroids, halftone textures, and smart visual resets.",
    visualDensity: 0.65,
    pacingVisual: "editorial_rhythmic",
    typographyStyle: "bold_condensed",
    typographyWeight: "black",
    typographyScale: 1.3,
    captionVisualStyle: "kinetic_highlight",
    accentColor: "#F59E0B",
    backgroundStyle: "dark_neutral",
    textureStyle: "paper_grain",
    colorMood: "dark_editorial",
    collageIntensity: 0.7,
    photoStyle: "polaroid",
    paperStyle: "torn_rough",
    newspaperStyle: "bold_headline",
    polaroidStyle: "shadowed",
    halftoneIntensity: 0.4,
    cutoutStyle: "sticker_border",
    shadowStyle: "layered_drop",
    borderStyle: "paper_deckle",
    transitionStyle: "paper_tear",
    motionIntensity: 0.7,
    zoomIntensity: 1.2,
    punchInFrequency: 0.6,
    brollFrequency: 0.5,
    talkingHeadRatio: 0.55,
    supportingVisualRatio: 0.45,
    graphicRatio: 0.35,
    diagramUsage: "selective",
    mapUsage: "selective",
    screenshotUsage: "selective",
    iconUsage: "frequent",
    microMotion: "floating_parallax",
    compositionStyle: "layered_collage",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "balanced",
    source: "STYLE_PRESET",
    confidence: 0.98,
    evidence: "Official OmniStrih signature editorial style profile",
    version: 1,
  },
  AI_KREATIVNY_EDITOR: {
    id: "AI_KREATIVNY_EDITOR",
    name: "AI Kreatívny Editor",
    description: "Dynamic AI-driven creative style with vibrant accents, kinetic motion, and expressive collage elements.",
    visualDensity: 0.8,
    pacingVisual: "fast_dynamic",
    typographyStyle: "kinetic_display",
    typographyWeight: "bold",
    typographyScale: 1.35,
    captionVisualStyle: "kinetic_highlight",
    accentColor: "#E11D48",
    backgroundStyle: "gradient_editorial",
    textureStyle: "halftone",
    colorMood: "vibrant_pop",
    collageIntensity: 0.85,
    photoStyle: "newspaper_cutout",
    paperStyle: "torn_rough",
    newspaperStyle: "vintage_article",
    polaroidStyle: "vintage_white",
    halftoneIntensity: 0.6,
    cutoutStyle: "subject_isolate",
    shadowStyle: "hard_offset",
    borderStyle: "solid_2px",
    transitionStyle: "whip",
    motionIntensity: 0.85,
    zoomIntensity: 1.25,
    punchInFrequency: 0.75,
    brollFrequency: 0.65,
    talkingHeadRatio: 0.45,
    supportingVisualRatio: 0.55,
    graphicRatio: 0.5,
    diagramUsage: "selective",
    mapUsage: "selective",
    screenshotUsage: "frequent",
    iconUsage: "frequent",
    microMotion: "snappy_pop",
    compositionStyle: "layered_collage",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "dense",
    source: "STYLE_PRESET",
    confidence: 0.95,
    evidence: "Maximum creative impact preset for social & marketing content",
    version: 1,
  },
  CINEMATIC: {
    id: "CINEMATIC",
    name: "Cinematic",
    description: "Elegant widescreen aesthetic with spacious layout, subtle letterboxing, warm tones, and smooth camera drift.",
    visualDensity: 0.35,
    pacingVisual: "calm_spacious",
    typographyStyle: "editorial_serif",
    typographyWeight: "medium",
    typographyScale: 1.15,
    captionVisualStyle: "minimal_clean",
    accentColor: "#D97706",
    backgroundStyle: "dark_neutral",
    textureStyle: "dust_scratches",
    colorMood: "cinematic_warm",
    collageIntensity: 0.2,
    photoStyle: "clean_frame",
    paperStyle: "none",
    newspaperStyle: "none",
    polaroidStyle: "none",
    halftoneIntensity: 0.0,
    cutoutStyle: "none",
    shadowStyle: "soft_ambient",
    borderStyle: "none",
    transitionStyle: "none",
    motionIntensity: 0.3,
    zoomIntensity: 1.1,
    punchInFrequency: 0.25,
    brollFrequency: 0.6,
    talkingHeadRatio: 0.4,
    supportingVisualRatio: 0.6,
    graphicRatio: 0.15,
    diagramUsage: "rare",
    mapUsage: "selective",
    screenshotUsage: "rare",
    iconUsage: "rare",
    microMotion: "smooth_drift",
    compositionStyle: "centered_focus",
    visualHierarchy: "minimalist_focus",
    negativeSpace: "generous",
    source: "STYLE_PRESET",
    confidence: 0.96,
    evidence: "Cinematic documentary look",
    version: 1,
  },
  CLEAN_PROFESSIONAL: {
    id: "CLEAN_PROFESSIONAL",
    name: "Clean Professional",
    description: "Sleek, high-trust corporate and educational aesthetic with clean cards, sharp typography, and subtle shadows.",
    visualDensity: 0.45,
    pacingVisual: "balanced",
    typographyStyle: "clean_sans",
    typographyWeight: "bold",
    typographyScale: 1.2,
    captionVisualStyle: "editorial_box",
    accentColor: "#2563EB",
    backgroundStyle: "light_clean",
    textureStyle: "clean",
    colorMood: "clean_light",
    collageIntensity: 0.3,
    photoStyle: "paper_card",
    paperStyle: "straight_card",
    newspaperStyle: "none",
    polaroidStyle: "none",
    halftoneIntensity: 0.0,
    cutoutStyle: "sticker_border",
    shadowStyle: "soft_ambient",
    borderStyle: "solid_2px",
    transitionStyle: "seamless_slide",
    motionIntensity: 0.4,
    zoomIntensity: 1.15,
    punchInFrequency: 0.4,
    brollFrequency: 0.4,
    talkingHeadRatio: 0.65,
    supportingVisualRatio: 0.35,
    graphicRatio: 0.3,
    diagramUsage: "frequent",
    mapUsage: "selective",
    screenshotUsage: "frequent",
    iconUsage: "frequent",
    microMotion: "subtle_drift",
    compositionStyle: "rule_of_thirds",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "generous",
    source: "STYLE_PRESET",
    confidence: 0.97,
    evidence: "Corporate and educational gold standard",
    version: 1,
  },
  SOCIAL_FAST: {
    id: "SOCIAL_FAST",
    name: "Social Fast (TikTok / Reels)",
    description: "High-retention social style featuring fast punch-ins, pop typography, frequent overlays, and maximum visual density.",
    visualDensity: 0.9,
    pacingVisual: "fast_dynamic",
    typographyStyle: "kinetic_display",
    typographyWeight: "black",
    typographyScale: 1.4,
    captionVisualStyle: "kinetic_highlight",
    accentColor: "#10B981",
    backgroundStyle: "dark_neutral",
    textureStyle: "halftone",
    colorMood: "vibrant_pop",
    collageIntensity: 0.9,
    photoStyle: "newspaper_cutout",
    paperStyle: "torn_rough",
    newspaperStyle: "bold_headline",
    polaroidStyle: "shadowed",
    halftoneIntensity: 0.5,
    cutoutStyle: "subject_isolate",
    shadowStyle: "hard_offset",
    borderStyle: "dashed",
    transitionStyle: "whip",
    motionIntensity: 0.9,
    zoomIntensity: 1.3,
    punchInFrequency: 0.85,
    brollFrequency: 0.7,
    talkingHeadRatio: 0.35,
    supportingVisualRatio: 0.65,
    graphicRatio: 0.6,
    diagramUsage: "selective",
    mapUsage: "selective",
    screenshotUsage: "frequent",
    iconUsage: "frequent",
    microMotion: "snappy_pop",
    compositionStyle: "layered_collage",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "dense",
    source: "STYLE_PRESET",
    confidence: 0.96,
    evidence: "Optimized for short-form video retention algorithms",
    version: 1,
  },
  DOCUMENTARY: {
    id: "DOCUMENTARY",
    name: "Documentary",
    description: "Historical and investigative layout with paper fragments, archive photos, maps, and rich texture overlays.",
    visualDensity: 0.55,
    pacingVisual: "editorial_rhythmic",
    typographyStyle: "editorial_serif",
    typographyWeight: "bold",
    typographyScale: 1.25,
    captionVisualStyle: "editorial_box",
    accentColor: "#D97706",
    backgroundStyle: "paper_texture",
    textureStyle: "newspaper",
    colorMood: "monochrome_newspaper",
    collageIntensity: 0.65,
    photoStyle: "polaroid",
    paperStyle: "torn_rough",
    newspaperStyle: "vintage_article",
    polaroidStyle: "vintage_white",
    halftoneIntensity: 0.7,
    cutoutStyle: "paper_edge",
    shadowStyle: "layered_drop",
    borderStyle: "paper_deckle",
    transitionStyle: "paper_tear",
    motionIntensity: 0.5,
    zoomIntensity: 1.15,
    punchInFrequency: 0.35,
    brollFrequency: 0.65,
    talkingHeadRatio: 0.5,
    supportingVisualRatio: 0.5,
    graphicRatio: 0.4,
    diagramUsage: "selective",
    mapUsage: "frequent",
    screenshotUsage: "selective",
    iconUsage: "selective",
    microMotion: "floating_parallax",
    compositionStyle: "layered_collage",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "balanced",
    source: "STYLE_PRESET",
    confidence: 0.95,
    evidence: "Investigative documentary and story breakdown",
    version: 1,
  },
  EDUCATIONAL: {
    id: "EDUCATIONAL",
    name: "Educational",
    description: "Diagram-first layout with step-by-step graphic popups, clear text cards, and clear visual hierarchy.",
    visualDensity: 0.5,
    pacingVisual: "balanced",
    typographyStyle: "clean_sans",
    typographyWeight: "bold",
    typographyScale: 1.25,
    captionVisualStyle: "editorial_box",
    accentColor: "#0EA5E9",
    backgroundStyle: "light_clean",
    textureStyle: "clean",
    colorMood: "clean_light",
    collageIntensity: 0.4,
    photoStyle: "paper_card",
    paperStyle: "straight_card",
    newspaperStyle: "none",
    polaroidStyle: "none",
    halftoneIntensity: 0.0,
    cutoutStyle: "sticker_border",
    shadowStyle: "soft_ambient",
    borderStyle: "solid_2px",
    transitionStyle: "seamless_slide",
    motionIntensity: 0.45,
    zoomIntensity: 1.15,
    punchInFrequency: 0.4,
    brollFrequency: 0.4,
    talkingHeadRatio: 0.6,
    supportingVisualRatio: 0.4,
    graphicRatio: 0.45,
    diagramUsage: "frequent",
    mapUsage: "selective",
    screenshotUsage: "frequent",
    iconUsage: "frequent",
    microMotion: "subtle_drift",
    compositionStyle: "split_screen",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "generous",
    source: "STYLE_PRESET",
    confidence: 0.97,
    evidence: "Optimized for knowledge transfer and tutorial clarity",
    version: 1,
  },
  PODCAST: {
    id: "PODCAST",
    name: "Podcast / Talking Head Focus",
    description: "Speaker-first style with minimal distractions, gentle punch-ins, and key phrase popups.",
    visualDensity: 0.3,
    pacingVisual: "calm_spacious",
    typographyStyle: "bold_condensed",
    typographyWeight: "bold",
    typographyScale: 1.2,
    captionVisualStyle: "kinetic_highlight",
    accentColor: "#8B5CF6",
    backgroundStyle: "dark_neutral",
    textureStyle: "clean",
    colorMood: "dark_editorial",
    collageIntensity: 0.2,
    photoStyle: "clean_frame",
    paperStyle: "none",
    newspaperStyle: "none",
    polaroidStyle: "none",
    halftoneIntensity: 0.0,
    cutoutStyle: "none",
    shadowStyle: "soft_ambient",
    borderStyle: "none",
    transitionStyle: "none",
    motionIntensity: 0.35,
    zoomIntensity: 1.15,
    punchInFrequency: 0.5,
    brollFrequency: 0.2,
    talkingHeadRatio: 0.8,
    supportingVisualRatio: 0.2,
    graphicRatio: 0.2,
    diagramUsage: "rare",
    mapUsage: "rare",
    screenshotUsage: "selective",
    iconUsage: "selective",
    microMotion: "breathe",
    compositionStyle: "centered_focus",
    visualHierarchy: "minimalist_focus",
    negativeSpace: "generous",
    source: "STYLE_PRESET",
    confidence: 0.98,
    evidence: "Long-form interview & podcast emphasis",
    version: 1,
  },
  NEWS_EDITORIAL: {
    id: "NEWS_EDITORIAL",
    name: "News / Editorial",
    description: "Broadcast editorial look with news ticker elements, headline cards, and newspaper fragments.",
    visualDensity: 0.6,
    pacingVisual: "editorial_rhythmic",
    typographyStyle: "bold_condensed",
    typographyWeight: "black",
    typographyScale: 1.3,
    captionVisualStyle: "editorial_box",
    accentColor: "#DC2626",
    backgroundStyle: "dark_neutral",
    textureStyle: "newspaper",
    colorMood: "monochrome_newspaper",
    collageIntensity: 0.6,
    photoStyle: "newspaper_cutout",
    paperStyle: "straight_card",
    newspaperStyle: "bold_headline",
    polaroidStyle: "shadowed",
    halftoneIntensity: 0.5,
    cutoutStyle: "paper_edge",
    shadowStyle: "hard_offset",
    borderStyle: "solid_2px",
    transitionStyle: "flash",
    motionIntensity: 0.6,
    zoomIntensity: 1.2,
    punchInFrequency: 0.55,
    brollFrequency: 0.5,
    talkingHeadRatio: 0.5,
    supportingVisualRatio: 0.5,
    graphicRatio: 0.4,
    diagramUsage: "selective",
    mapUsage: "frequent",
    screenshotUsage: "frequent",
    iconUsage: "frequent",
    microMotion: "snappy_pop",
    compositionStyle: "rule_of_thirds",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "balanced",
    source: "STYLE_PRESET",
    confidence: 0.96,
    evidence: "Newsroom breakdown & current affairs",
    version: 1,
  },
  MINIMAL: {
    id: "MINIMAL",
    name: "Minimal",
    description: "Zero noise, pristine layout focusing on clean speaker frames and essential captions only.",
    visualDensity: 0.1,
    pacingVisual: "calm_spacious",
    typographyStyle: "minimal_modern",
    typographyWeight: "medium",
    typographyScale: 1.0,
    captionVisualStyle: "minimal_clean",
    accentColor: "#6B7280",
    backgroundStyle: "dark_neutral",
    textureStyle: "clean",
    colorMood: "dark_editorial",
    collageIntensity: 0.0,
    photoStyle: "clean_frame",
    paperStyle: "none",
    newspaperStyle: "none",
    polaroidStyle: "none",
    halftoneIntensity: 0.0,
    cutoutStyle: "none",
    shadowStyle: "none",
    borderStyle: "none",
    transitionStyle: "none",
    motionIntensity: 0.1,
    zoomIntensity: 1.05,
    punchInFrequency: 0.1,
    brollFrequency: 0.1,
    talkingHeadRatio: 0.9,
    supportingVisualRatio: 0.1,
    graphicRatio: 0.05,
    diagramUsage: "none",
    mapUsage: "none",
    screenshotUsage: "rare",
    iconUsage: "none",
    microMotion: "static",
    compositionStyle: "centered_focus",
    visualHierarchy: "minimalist_focus",
    negativeSpace: "generous",
    source: "STYLE_PRESET",
    confidence: 0.99,
    evidence: "Minimalist ultra-clean profile",
    version: 1,
  },
  CUSTOM: {
    id: "CUSTOM",
    name: "Custom Style Profile",
    description: "User-configured custom visual DNA parameters.",
    visualDensity: 0.5,
    pacingVisual: "balanced",
    typographyStyle: "bold_condensed",
    typographyWeight: "bold",
    typographyScale: 1.2,
    captionVisualStyle: "kinetic_highlight",
    accentColor: "#F59E0B",
    backgroundStyle: "dark_neutral",
    textureStyle: "paper_grain",
    colorMood: "dark_editorial",
    collageIntensity: 0.5,
    photoStyle: "paper_card",
    paperStyle: "straight_card",
    newspaperStyle: "bold_headline",
    polaroidStyle: "shadowed",
    halftoneIntensity: 0.2,
    cutoutStyle: "sticker_border",
    shadowStyle: "layered_drop",
    borderStyle: "solid_2px",
    transitionStyle: "paper_tear",
    motionIntensity: 0.5,
    zoomIntensity: 1.15,
    punchInFrequency: 0.5,
    brollFrequency: 0.4,
    talkingHeadRatio: 0.6,
    supportingVisualRatio: 0.4,
    graphicRatio: 0.3,
    diagramUsage: "selective",
    mapUsage: "selective",
    screenshotUsage: "selective",
    iconUsage: "frequent",
    microMotion: "subtle_drift",
    compositionStyle: "layered_collage",
    visualHierarchy: "bold_primary_secondary",
    negativeSpace: "balanced",
    source: "USER",
    confidence: 1.0,
    evidence: "User customized settings",
    version: 1,
  },
};
