import { CaptionSegment, EraserZone } from "../types";

export interface DemoVideo {
  id: string;
  titleSk: string;
  titleEn: string;
  category: string;
  url: string;
  duration: number;
  sampleTranscriptSk: string;
  sampleTranscriptEn: string;
  defaultCaptionsSk: CaptionSegment[];
  defaultCaptionsEn: CaptionSegment[];
  suggestedEraserZones?: EraserZone[];
}

export const DEMO_VIDEOS: DemoVideo[] = [
  {
    id: "creator-tips",
    titleSk: "Tvorca obsahu (Talking Head)",
    titleEn: "Content Creator (Talking Head)",
    category: "TikTok / Reels",
    url: "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4",
    duration: 15,
    sampleTranscriptSk: "Ako ušetriť 95% času na strih videa bez platenia drahých appiek.",
    sampleTranscriptEn: "How to save 95% of editing time without paying for expensive tools.",
    suggestedEraserZones: [
      {
        id: "wm-tiktok-bottom",
        name: "TikTok Vodoznak (Vpravo dole)",
        type: "watermark",
        x: 0.72,
        y: 0.88,
        width: 0.25,
        height: 0.08,
        enabled: true,
        feather: 3,
      },
      {
        id: "subtitles-burned",
        name: "Spálené staré titulky (Spodný pás)",
        type: "subtitles",
        x: 0.12,
        y: 0.82,
        width: 0.76,
        height: 0.07,
        enabled: false,
        feather: 4,
      },
    ],
    defaultCaptionsSk: [
      {
        id: "c1",
        start: 0.0,
        end: 2.8,
        text: "Ako ušetriť 95% času na strih videa",
        emoji: "⚡",
        words: [
          { word: "Ako", start: 0.0, end: 0.4, highlight: false },
          { word: "ušetriť", start: 0.4, end: 0.9, highlight: false },
          { word: "95%", start: 0.9, end: 1.6, highlight: true },
          { word: "času", start: 1.6, end: 2.1, highlight: false },
          { word: "na strih", start: 2.1, end: 2.8, highlight: false },
        ],
      },
      {
        id: "c2",
        start: 3.0,
        end: 6.2,
        text: "Už žiadne platenie drahých appiek!",
        emoji: "💸",
        words: [
          { word: "Už", start: 3.0, end: 3.4, highlight: false },
          { word: "žiadne", start: 3.4, end: 4.1, highlight: false },
          { word: "platenie", start: 4.1, end: 4.8, highlight: false },
          { word: "drahých", start: 4.8, end: 5.5, highlight: false },
          { word: "appiek!", start: 5.5, end: 6.2, highlight: true },
        ],
      },
      {
        id: "c3",
        start: 6.5,
        end: 10.0,
        text: "Inteligentný B-Roll a čistý zvuk jedným klikom",
        emoji: "🎯",
        words: [
          { word: "Inteligentný", start: 6.5, end: 7.3, highlight: true },
          { word: "B-Roll", start: 7.3, end: 8.1, highlight: false },
          { word: "a čistý", start: 8.1, end: 8.8, highlight: false },
          { word: "zvuk", start: 8.8, end: 9.3, highlight: true },
          { word: "klikom", start: 9.3, end: 10.0, highlight: false },
        ],
      },
      {
        id: "c4",
        start: 10.2,
        end: 14.5,
        text: "Vyskúšaj to teraz hneď a zadarmo!",
        emoji: "🚀",
        words: [
          { word: "Vyskúšaj", start: 10.2, end: 11.0, highlight: false },
          { word: "to teraz", start: 11.0, end: 12.0, highlight: false },
          { word: "hneď a", start: 12.0, end: 13.0, highlight: false },
          { word: "zadarmo!", start: 13.0, end: 14.5, highlight: true },
        ],
      },
    ],
    defaultCaptionsEn: [
      {
        id: "c1-en",
        start: 0.0,
        end: 2.8,
        text: "How to save 95% of editing time",
        emoji: "⚡",
        words: [
          { word: "How", start: 0.0, end: 0.4, highlight: false },
          { word: "to save", start: 0.4, end: 1.0, highlight: false },
          { word: "95%", start: 1.0, end: 1.7, highlight: true },
          { word: "of editing", start: 1.7, end: 2.2, highlight: false },
          { word: "time", start: 2.2, end: 2.8, highlight: false },
        ],
      },
      {
        id: "c2-en",
        start: 3.0,
        end: 6.2,
        text: "Stop paying for expensive video apps!",
        emoji: "💸",
        words: [
          { word: "Stop", start: 3.0, end: 3.5, highlight: false },
          { word: "paying", start: 3.5, end: 4.2, highlight: false },
          { word: "for expensive", start: 4.2, end: 5.1, highlight: false },
          { word: "video", start: 5.1, end: 5.6, highlight: false },
          { word: "apps!", start: 5.6, end: 6.2, highlight: true },
        ],
      },
      {
        id: "c3-en",
        start: 6.5,
        end: 10.0,
        text: "Contextual B-roll and clean voiceover",
        emoji: "🎯",
        words: [
          { word: "Contextual", start: 6.5, end: 7.3, highlight: true },
          { word: "B-roll", start: 7.3, end: 8.2, highlight: false },
          { word: "and clean", start: 8.2, end: 9.0, highlight: false },
          { word: "voiceover", start: 9.0, end: 10.0, highlight: true },
        ],
      },
      {
        id: "c4-en",
        start: 10.2,
        end: 14.5,
        text: "Try it right now for free!",
        emoji: "🚀",
        words: [
          { word: "Try it", start: 10.2, end: 11.2, highlight: false },
          { word: "right now", start: 11.2, end: 12.5, highlight: false },
          { word: "for free!", start: 12.5, end: 14.5, highlight: true },
        ],
      },
    ],
  },
  {
    id: "podcast-clip",
    titleSk: "Podcast & Rozhovor",
    titleEn: "Podcast & Interview",
    category: "YouTube / Shorts",
    url: "https://vjs.zencdn.net/v/oceans.mp4",
    duration: 15,
    sampleTranscriptSk: "Tajomstvo virality je dynamický strih, smart zoom a titulky.",
    sampleTranscriptEn: "The secret to virality is dynamic pacing, smart zoom, and captions.",
    suggestedEraserZones: [
      {
        id: "wm-top-left",
        name: "Logo v rohu (Vľavo hore)",
        type: "watermark",
        x: 0.04,
        y: 0.04,
        width: 0.2,
        height: 0.07,
        enabled: true,
        feather: 3,
      },
    ],
    defaultCaptionsSk: [
      {
        id: "p1",
        start: 0.0,
        end: 3.2,
        text: "Tajomstvo virality podcastu?",
        emoji: "🎙️",
        words: [
          { word: "Tajomstvo", start: 0.0, end: 0.8, highlight: true },
          { word: "virality", start: 0.8, end: 1.8, highlight: true },
          { word: "podcastu?", start: 1.8, end: 3.2, highlight: false },
        ],
      },
      {
        id: "p2",
        start: 3.4,
        end: 7.0,
        text: "Dynamický strih a punch-in zoom na dôležité slová",
        emoji: "🔍",
        words: [
          { word: "Dynamický", start: 3.4, end: 4.2, highlight: false },
          { word: "strih", start: 4.2, end: 4.9, highlight: true },
          { word: "a punch-in", start: 4.9, end: 5.6, highlight: false },
          { word: "zoom na", start: 5.6, end: 6.2, highlight: false },
          { word: "slová", start: 6.2, end: 7.0, highlight: true },
        ],
      },
      {
        id: "p3",
        start: 7.2,
        end: 11.5,
        text: "Divák nesmie ani na sekundu odtrhnúť zrak",
        emoji: "👀",
        words: [
          { word: "Divák", start: 7.2, end: 7.9, highlight: false },
          { word: "nesmie", start: 7.9, end: 8.8, highlight: false },
          { word: "ani na", start: 8.8, end: 9.5, highlight: false },
          { word: "sekundu", start: 9.5, end: 10.3, highlight: true },
          { word: "zrak", start: 10.3, end: 11.5, highlight: false },
        ],
      },
      {
        id: "p4",
        start: 11.8,
        end: 14.8,
        text: "Presne toto robí OmniStrih úplne sám!",
        emoji: "🔥",
        words: [
          { word: "Presne", start: 11.8, end: 12.4, highlight: false },
          { word: "toto", start: 12.4, end: 13.0, highlight: false },
          { word: "robí", start: 13.0, end: 13.6, highlight: false },
          { word: "OmniStrih", start: 13.6, end: 14.2, highlight: true },
          { word: "sám!", start: 14.2, end: 14.8, highlight: true },
        ],
      },
    ],
    defaultCaptionsEn: [
      {
        id: "p1-en",
        start: 0.0,
        end: 3.2,
        text: "The secret to podcast virality?",
        emoji: "🎙️",
        words: [
          { word: "The secret", start: 0.0, end: 0.9, highlight: true },
          { word: "to podcast", start: 0.9, end: 1.8, highlight: false },
          { word: "virality?", start: 1.8, end: 3.2, highlight: true },
        ],
      },
      {
        id: "p2-en",
        start: 3.4,
        end: 7.0,
        text: "Fast punchy cuts and automatic zoom-ins",
        emoji: "🔍",
        words: [
          { word: "Fast", start: 3.4, end: 4.1, highlight: false },
          { word: "punchy cuts", start: 4.1, end: 5.2, highlight: true },
          { word: "and automatic", start: 5.2, end: 6.0, highlight: false },
          { word: "zoom-ins", start: 6.0, end: 7.0, highlight: true },
        ],
      },
      {
        id: "p3-en",
        start: 7.2,
        end: 11.5,
        text: "Viewers won't swipe away for a single second",
        emoji: "👀",
        words: [
          { word: "Viewers", start: 7.2, end: 8.0, highlight: false },
          { word: "won't swipe", start: 8.0, end: 9.2, highlight: true },
          { word: "away for", start: 9.2, end: 10.1, highlight: false },
          { word: "a single second", start: 10.1, end: 11.5, highlight: true },
        ],
      },
      {
        id: "p4-en",
        start: 11.8,
        end: 14.8,
        text: "OmniCut automates this entirely!",
        emoji: "🔥",
        words: [
          { word: "OmniCut", start: 11.8, end: 12.8, highlight: true },
          { word: "automates", start: 12.8, end: 13.8, highlight: false },
          { word: "this entirely!", start: 13.8, end: 14.8, highlight: true },
        ],
      },
    ],
  },
  {
    id: "lifestyle-vlog",
    titleSk: "Vlog & Prezentácia",
    titleEn: "Vlog & Showcase",
    category: "Instagram / Feed",
    url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    duration: 15,
    sampleTranscriptSk: "Pozri sa na tento výsledok! Všetko vygenerované za 2 sekundy.",
    sampleTranscriptEn: "Look at this final result! Everything generated in two seconds.",
    suggestedEraserZones: [
      {
        id: "sub-banner-hard",
        name: "Pôvodné tvrdé titulky (Stred/Dole)",
        type: "subtitles",
        x: 0.15,
        y: 0.76,
        width: 0.7,
        height: 0.09,
        enabled: true,
        feather: 3,
      },
    ],
    defaultCaptionsSk: [
      {
        id: "v1",
        start: 0.0,
        end: 3.5,
        text: "Neuveriteľný výsledok za dve sekundy!",
        emoji: "✨",
        words: [
          { word: "Neuveriteľný", start: 0.0, end: 1.0, highlight: true },
          { word: "výsledok", start: 1.0, end: 1.9, highlight: false },
          { word: "za dve", start: 1.9, end: 2.7, highlight: false },
          { word: "sekundy!", start: 2.7, end: 3.5, highlight: true },
        ],
      },
      {
        id: "v2",
        start: 3.8,
        end: 7.5,
        text: "Žiadne zložité nastavovanie ani Premiere Pro",
        emoji: "💻",
        words: [
          { word: "Žiadne", start: 3.8, end: 4.5, highlight: false },
          { word: "zložité", start: 4.5, end: 5.3, highlight: false },
          { word: "nastavovanie", start: 5.3, end: 6.4, highlight: false },
          { word: "ani Premiere", start: 6.4, end: 7.5, highlight: true },
        ],
      },
      {
        id: "v3",
        start: 7.8,
        end: 11.2,
        text: "Vodoznaky a staré titulky vymazané bez rozmazania",
        emoji: "🧼",
        words: [
          { word: "Vodoznaky", start: 7.8, end: 8.8, highlight: true },
          { word: "a staré", start: 8.8, end: 9.5, highlight: false },
          { word: "titulky", start: 9.5, end: 10.3, highlight: false },
          { word: "vymazané!", start: 10.3, end: 11.2, highlight: true },
        ],
      },
      {
        id: "v4",
        start: 11.5,
        end: 14.8,
        text: "Čistá kvalita v rozlíšení 4K pripravená na export",
        emoji: "💎",
        words: [
          { word: "Čistá", start: 11.5, end: 12.1, highlight: false },
          { word: "kvalita", start: 12.1, end: 12.8, highlight: true },
          { word: "v 4K", start: 12.8, end: 13.7, highlight: true },
          { word: "na export", start: 13.7, end: 14.8, highlight: false },
        ],
      },
    ],
    defaultCaptionsEn: [
      {
        id: "v1-en",
        start: 0.0,
        end: 3.5,
        text: "Incredible result in just two seconds!",
        emoji: "✨",
        words: [
          { word: "Incredible", start: 0.0, end: 1.0, highlight: true },
          { word: "result in", start: 1.0, end: 2.0, highlight: false },
          { word: "just two", start: 2.0, end: 2.8, highlight: false },
          { word: "seconds!", start: 2.8, end: 3.5, highlight: true },
        ],
      },
      {
        id: "v2-en",
        start: 3.8,
        end: 7.5,
        text: "No complicated editing software needed",
        emoji: "💻",
        words: [
          { word: "No", start: 3.8, end: 4.4, highlight: false },
          { word: "complicated", start: 4.4, end: 5.5, highlight: false },
          { word: "software", start: 5.5, end: 6.5, highlight: false },
          { word: "needed", start: 6.5, end: 7.5, highlight: true },
        ],
      },
      {
        id: "v3-en",
        start: 7.8,
        end: 11.2,
        text: "Watermarks and old captions erased with zero blur",
        emoji: "🧼",
        words: [
          { word: "Watermarks", start: 7.8, end: 8.8, highlight: true },
          { word: "and old", start: 8.8, end: 9.5, highlight: false },
          { word: "captions", start: 9.5, end: 10.3, highlight: false },
          { word: "erased!", start: 10.3, end: 11.2, highlight: true },
        ],
      },
      {
        id: "v4-en",
        start: 11.5,
        end: 14.8,
        text: "Pristine 4K quality ready for export",
        emoji: "💎",
        words: [
          { word: "Pristine", start: 11.5, end: 12.3, highlight: true },
          { word: "quality", start: 12.3, end: 13.2, highlight: false },
          { word: "ready for", start: 13.2, end: 14.0, highlight: false },
          { word: "export", start: 14.0, end: 14.8, highlight: true },
        ],
      },
    ],
  },
];
