import { EditDNAModel, EditingMemoryRule, EditorBrainState, PotentialPreferencePrompt } from "../types";

export const DEFAULT_EDIT_DNA_PROFILES: EditDNAModel[] = [
  {
    id: "profile-personal",
    profileName: "Personal",
    profileType: "Personal",
    descriptionSk: "Vyvážený osobný štýl s čistými titulkami a jemnými zvukovými efektmi",
    descriptionEn: "Balanced personal editing style with clean captions and subtle SFX",
    icon: "👤",
    pacing: "BALANCED",
    jumpCuts: "MEDIUM",
    jumpCutIntensity: 0.55,
    silenceThreshold: 0.60,
    pauseTolerance: 0.60,
    fillerWordBehavior: "REMOVE_ALL",
    zoomFrequency: "MEDIUM",
    zoomIntensity: 1.15,
    captionStyle: "MINIMAL_CLEAN",
    captionSize: 1.0,
    captionPosition: "bottom",
    captionDensity: "MEDIUM",
    preferredFont: "Inter / Modern Sans",
    preferredColors: {
      primary: "#38bdf8",
      secondary: "#0284c7",
      highlight: "#fde047",
    },
    bRollFrequency: "MEDIUM",
    bRollStyle: "CONTEXTUAL",
    sfxFrequency: "LOW",
    sfxIntensity: "SUBTLE",
    musicVolume: 0.14,
    musicDucking: true,
    transitionPreference: "dissolve",
    hookIntensity: "MEDIUM",
    preferredAspectRatio: "9:16",
    preferredExportQuality: "1080p",
  },
  {
    id: "profile-youtube",
    profileName: "YouTube",
    profileType: "YouTube",
    descriptionSk: "Štruktúrovaný 16:9 strih optimalizovaný na dlhé udržanie pozornosti",
    descriptionEn: "Structured 16:9 pacing optimized for long-form retention and depth",
    icon: "🔴",
    pacing: "BALANCED",
    jumpCuts: "MEDIUM",
    jumpCutIntensity: 0.60,
    silenceThreshold: 0.55,
    pauseTolerance: 0.55,
    fillerWordBehavior: "REMOVE_ALL",
    zoomFrequency: "MEDIUM",
    zoomIntensity: 1.20,
    captionStyle: "CINEMATIC",
    captionSize: 1.1,
    captionPosition: "bottom",
    captionDensity: "MEDIUM",
    preferredFont: "Montserrat / Bold Display",
    preferredColors: {
      primary: "#f43f5e",
      secondary: "#e11d48",
      highlight: "#fbbf24",
    },
    bRollFrequency: "HIGH",
    bRollStyle: "CONTEXTUAL",
    sfxFrequency: "MEDIUM",
    sfxIntensity: "ENERGETIC",
    musicVolume: 0.16,
    musicDucking: true,
    transitionPreference: "whip_pan",
    hookIntensity: "HIGH",
    preferredAspectRatio: "16:9",
    preferredExportQuality: "4K",
  },
  {
    id: "profile-shorts",
    profileName: "Shorts",
    profileType: "Shorts",
    descriptionSk: "Hyper-kinetický vertikálny 9:16 formát (TikTok / Reels / Shorts) s virálnym strihom",
    descriptionEn: "Hyper-kinetic vertical 9:16 format with punchy Hormozi captions & fast hooks",
    icon: "📱",
    pacing: "FAST",
    jumpCuts: "AGGRESSIVE",
    jumpCutIntensity: 0.85,
    silenceThreshold: 0.38,
    pauseTolerance: 0.38,
    fillerWordBehavior: "REMOVE_ALL",
    zoomFrequency: "HIGH",
    zoomIntensity: 1.28,
    captionStyle: "HORMOZI",
    captionSize: 1.25,
    captionPosition: "middle",
    captionDensity: "HIGH",
    preferredFont: "Syne / Bold Punch",
    preferredColors: {
      primary: "#eab308",
      secondary: "#ca8a04",
      highlight: "#22c55e",
    },
    bRollFrequency: "HIGH",
    bRollStyle: "DYNAMIC",
    sfxFrequency: "HIGH",
    sfxIntensity: "ENERGETIC",
    musicVolume: 0.22,
    musicDucking: true,
    transitionPreference: "zoom_through",
    hookIntensity: "HIGH",
    preferredAspectRatio: "9:16",
    preferredExportQuality: "1080p",
  },
  {
    id: "profile-client-a",
    profileName: "Client A",
    profileType: "Client A",
    descriptionSk: "Konzervatívny firemný profil: čisté prechody, decentné titulky, minimálny ruch",
    descriptionEn: "Corporate executive profile: clean dissolves, subtle captions, minimal SFX",
    icon: "💼",
    pacing: "BALANCED",
    jumpCuts: "MINIMAL",
    jumpCutIntensity: 0.35,
    silenceThreshold: 0.75,
    pauseTolerance: 0.75,
    fillerWordBehavior: "REVIEW",
    zoomFrequency: "LOW",
    zoomIntensity: 1.08,
    captionStyle: "MINIMAL_CLEAN",
    captionSize: 0.95,
    captionPosition: "bottom",
    captionDensity: "MINIMAL",
    preferredFont: "Inter / Clean Minimal",
    preferredColors: {
      primary: "#3b82f6",
      secondary: "#1d4ed8",
      highlight: "#93c5fd",
    },
    bRollFrequency: "LOW",
    bRollStyle: "MINIMAL",
    sfxFrequency: "MINIMAL",
    sfxIntensity: "SUBTLE",
    musicVolume: 0.10,
    musicDucking: true,
    transitionPreference: "crossfade",
    hookIntensity: "SUBTLE",
    preferredAspectRatio: "16:9",
    preferredExportQuality: "4K",
  },
  {
    id: "profile-client-b",
    profileName: "Client B",
    profileType: "Client B",
    descriptionSk: "Moderná agentúra: dynamický strih, Cyber Glitch, Submagic štýl a výrazné SFX",
    descriptionEn: "Modern creative agency: dynamic pacing, RGB glitch, Submagic captions",
    icon: "⚡",
    pacing: "FAST",
    jumpCuts: "AGGRESSIVE",
    jumpCutIntensity: 0.80,
    silenceThreshold: 0.42,
    pauseTolerance: 0.42,
    fillerWordBehavior: "REMOVE_ALL",
    zoomFrequency: "HIGH",
    zoomIntensity: 1.30,
    captionStyle: "submagic-viral",
    captionSize: 1.20,
    captionPosition: "middle",
    captionDensity: "HIGH",
    preferredFont: "Syne / ExtraBold",
    preferredColors: {
      primary: "#a855f7",
      secondary: "#7e22ce",
      highlight: "#06b6d4",
    },
    bRollFrequency: "HIGH",
    bRollStyle: "TORN_PAPER",
    sfxFrequency: "HIGH",
    sfxIntensity: "ENERGETIC",
    musicVolume: 0.20,
    musicDucking: true,
    transitionPreference: "glitch",
    hookIntensity: "HIGH",
    preferredAspectRatio: "9:16",
    preferredExportQuality: "1080p",
  },
  {
    id: "profile-educational",
    profileName: "Educational",
    profileType: "Educational",
    descriptionSk: "Vzdelávací a technický obsah s vyššou toleranciou na pauzy pre pochopenie",
    descriptionEn: "Educational and technical masterclass pacing with optimal thought pauses",
    icon: "🎓",
    pacing: "BALANCED",
    jumpCuts: "MEDIUM",
    jumpCutIntensity: 0.50,
    silenceThreshold: 0.70,
    pauseTolerance: 0.70,
    fillerWordBehavior: "REMOVE_ALL",
    zoomFrequency: "LOW",
    zoomIntensity: 1.12,
    captionStyle: "MINIMAL_CLEAN",
    captionSize: 1.05,
    captionPosition: "bottom",
    captionDensity: "MEDIUM",
    preferredFont: "JetBrains Mono / Code",
    preferredColors: {
      primary: "#10b981",
      secondary: "#047857",
      highlight: "#fde047",
    },
    bRollFrequency: "MEDIUM",
    bRollStyle: "CONTEXTUAL",
    sfxFrequency: "LOW",
    sfxIntensity: "SUBTLE",
    musicVolume: 0.08,
    musicDucking: true,
    transitionPreference: "split_horizontal",
    hookIntensity: "MEDIUM",
    preferredAspectRatio: "16:9",
    preferredExportQuality: "1080p",
  },
  {
    id: "profile-cinematic",
    profileName: "Cinematic",
    profileType: "Cinematic",
    descriptionSk: "Filmové prelnutia, hlboké tóny, organické svetelné záblesky a pomalší rytmus",
    descriptionEn: "Film aesthetic, deep optical flares, 24fps rhythm and natural breathing room",
    icon: "🎬",
    pacing: "CINEMATIC",
    jumpCuts: "MINIMAL",
    jumpCutIntensity: 0.25,
    silenceThreshold: 0.90,
    pauseTolerance: 0.90,
    fillerWordBehavior: "KEEP_NATURAL",
    zoomFrequency: "LOW",
    zoomIntensity: 1.10,
    captionStyle: "CINEMATIC",
    captionSize: 0.90,
    captionPosition: "bottom",
    captionDensity: "MINIMAL",
    preferredFont: "Playfair Display / Serif",
    preferredColors: {
      primary: "#f59e0b",
      secondary: "#b45309",
      highlight: "#ffffff",
    },
    bRollFrequency: "HIGH",
    bRollStyle: "CONTEXTUAL",
    sfxFrequency: "MEDIUM",
    sfxIntensity: "CINEMATIC",
    musicVolume: 0.18,
    musicDucking: true,
    transitionPreference: "light_leak",
    hookIntensity: "SUBTLE",
    preferredAspectRatio: "16:9",
    preferredExportQuality: "4K",
  },
];

export const INITIAL_LEARNED_RULES: EditingMemoryRule[] = [
  {
    id: "rule-1",
    ruleSk: "Užívateľ preferuje zachovať 0.65s pauzy pred dôležitými číselnými dátami",
    ruleEn: "User prefers preserving 0.65s pauses before key numerical statements",
    category: "PACING",
    occurrences: 6,
    confidence: 0.94,
    isActive: true,
    explicitlyConfirmedByUser: true,
    createdAt: "2026-09-18",
  },
  {
    id: "rule-2",
    ruleSk: "Pri prechodoch medzi odlišnými témami uprednostniť Whip Pan namiesto Dissolve",
    ruleEn: "On topic transitions, prefer Whip Pan over Soft Dissolve",
    category: "TRANSITIONS",
    occurrences: 4,
    confidence: 0.88,
    isActive: true,
    explicitlyConfirmedByUser: true,
    createdAt: "2026-09-19",
  },
  {
    id: "rule-3",
    ruleSk: "Titulky v strede obrazovky používať len na prvých 3 sekundách (Hook)",
    ruleEn: "Position center captions exclusively during the initial 3 seconds hook",
    category: "CAPTIONS",
    occurrences: 8,
    confidence: 0.97,
    isActive: true,
    explicitlyConfirmedByUser: true,
    createdAt: "2026-09-20",
  },
];

export const INITIAL_POTENTIAL_PREFERENCES: PotentialPreferencePrompt[] = [
  {
    id: "pref-prompt-1",
    category: "CUTS",
    titleSk: "Zvýšenie tolerancie ticha na 0.65s",
    titleEn: "Increase pause tolerance to 0.65s",
    triggerReasonSk: "V posledných 3 strihoch ste manuálne predĺžili pauzu medzi vetami z 0.40s na 0.65s.",
    triggerReasonEn: "You manually extended inter-sentence pause tolerance from 0.40s to 0.65s across 3 consecutive cuts.",
    fieldName: "pauseTolerance",
    detectedValue: 0.65,
    previousValue: 0.40,
    occurrencesCount: 3,
    targetProfileId: "profile-youtube",
    createdAt: "Práve teraz",
  },
  {
    id: "pref-prompt-2",
    category: "CAPTIONS",
    titleSk: "Zmena primárnej farby titulkov na Neónovú Žltú (#EAB308)",
    titleEn: "Set primary caption accent to Neon Yellow (#EAB308)",
    triggerReasonSk: "Zvolili ste žlté zvýraznenie kľúčových slov namiesto modrej v 4 po sebe idúcich klipoch.",
    triggerReasonEn: "You chose yellow keyword highlighting instead of blue across 4 consecutive clips.",
    fieldName: "preferredColors",
    detectedValue: { primary: "#eab308", secondary: "#ca8a04", highlight: "#22c55e" },
    previousValue: { primary: "#38bdf8", secondary: "#0284c7", highlight: "#fde047" },
    occurrencesCount: 4,
    targetProfileId: "profile-shorts",
    createdAt: "Pred 5 min",
  },
];
