import { TransitionPreset, TransitionEasing, TransitionType } from "../types";

export const TRANSITION_PRESETS: TransitionPreset[] = [
  // 1. CLASSIC & DISSOLVE
  {
    id: "preset-dissolve",
    nameSk: "Jemné Rozpustenie",
    nameEn: "Soft Dissolve",
    category: "CLASSIC",
    type: "dissolve",
    defaultDuration: 0.45,
    defaultEasing: "ease_in_out",
    easingCurve: [0.42, 0, 0.58, 1],
    descriptionSk: "Plynulý prechod zmäkčujúci strih medzi dvoma zábermi",
    descriptionEn: "Smooth opacity blending between consecutive clips",
    icon: "🌫️",
    recommendedSfx: "none",
  },
  {
    id: "preset-crossfade",
    nameSk: "Kinematický Crossfade",
    nameEn: "Cinematic Crossfade",
    category: "CLASSIC",
    type: "crossfade",
    defaultDuration: 0.6,
    defaultEasing: "cinematic_smooth",
    easingCurve: [0.25, 1, 0.5, 1],
    descriptionSk: "Filmové prelnutie s jemnou hĺbkou svetla",
    descriptionEn: "Film-like blending with rich tonal depth",
    icon: "🎬",
    recommendedSfx: "none",
  },

  // 2. DYNAMIC ZOOM & PUNCH
  {
    id: "preset-zoom-through",
    nameSk: "Zoom-Through (Prelet)",
    nameEn: "Zoom-Through",
    category: "DYNAMIC_ZOOM",
    type: "zoom_through",
    defaultDuration: 0.35,
    defaultEasing: "spring",
    easingCurve: [0.16, 1, 0.3, 1],
    descriptionSk: "Bleskový prelet do ďalšieho záberu s hyper-kinetickým priblížením",
    descriptionEn: "High-speed punch-through warp into the next scene",
    icon: "🚀",
    recommendedSfx: "whoosh",
  },
  {
    id: "preset-zoom-in",
    nameSk: "Dynamický Zoom In",
    nameEn: "Dynamic Zoom In",
    category: "DYNAMIC_ZOOM",
    type: "zoom_in",
    defaultDuration: 0.3,
    defaultEasing: "cinematic_smooth",
    easingCurve: [0.25, 1, 0.5, 1],
    descriptionSk: "Optické priblíženie na stred obrazu",
    descriptionEn: "Forward optical scale push into focal point",
    icon: "🔍",
    recommendedSfx: "swish",
  },
  {
    id: "preset-zoom-out",
    nameSk: "Optický Zoom Out",
    nameEn: "Optical Zoom Out",
    category: "DYNAMIC_ZOOM",
    type: "zoom_out",
    defaultDuration: 0.35,
    defaultEasing: "ease_out",
    easingCurve: [0, 0, 0.2, 1],
    descriptionSk: "Odtiahnutie kamery s odhalením nového kontextu",
    descriptionEn: "Pull-back camera perspective revealing new framing",
    icon: "🔭",
    recommendedSfx: "swish",
  },

  // 3. KINETIC SLIDE & WHIP
  {
    id: "preset-slide-left",
    nameSk: "Kinetický Slide Doľava",
    nameEn: "Kinetic Slide Left",
    category: "KINETIC_SLIDE",
    type: "slide_left",
    defaultDuration: 0.3,
    defaultEasing: "spring",
    easingCurve: [0.175, 0.885, 0.32, 1.275],
    descriptionSk: "Svižný posun záberu z pravej strany doľava",
    descriptionEn: "Snappy horizontal lateral sweep from right to left",
    icon: "◀️",
    recommendedSfx: "whoosh",
  },
  {
    id: "preset-slide-right",
    nameSk: "Kinetický Slide Doprava",
    nameEn: "Kinetic Slide Right",
    category: "KINETIC_SLIDE",
    type: "slide_right",
    defaultDuration: 0.3,
    defaultEasing: "spring",
    easingCurve: [0.175, 0.885, 0.32, 1.275],
    descriptionSk: "Posun záberu z ľavej strany doprava",
    descriptionEn: "Snappy horizontal sweep from left to right",
    icon: "▶️",
    recommendedSfx: "whoosh",
  },
  {
    id: "preset-slide-up",
    nameSk: "Vertikálny Slide Nahor",
    nameEn: "Vertical Slide Up",
    category: "KINETIC_SLIDE",
    type: "slide_up",
    defaultDuration: 0.28,
    defaultEasing: "cinematic_smooth",
    easingCurve: [0.25, 1, 0.5, 1],
    descriptionSk: "TikTok / Reels posun zdola nahor",
    descriptionEn: "Vertical story scroll swipe from bottom to top",
    icon: "🔼",
    recommendedSfx: "swish",
  },
  {
    id: "preset-whip-pan",
    nameSk: "Whip Pan (Švih Kamery)",
    nameEn: "Whip Pan",
    category: "KINETIC_SLIDE",
    type: "whip_pan",
    defaultDuration: 0.22,
    defaultEasing: "spring",
    easingCurve: [0.7, 0, 0.3, 1],
    descriptionSk: "Extrémne rýchly rotačný pohyb kamery so stopami rýchlosti",
    descriptionEn: "High-speed camera pan with dynamic motion blur trails",
    icon: "⚡",
    recommendedSfx: "whip_snap",
  },

  // 4. FILMIC & ORGANIC
  {
    id: "preset-light-leak",
    nameSk: "Svetelný Záblesk (Light Leak)",
    nameEn: "Light Leak & Flare",
    category: "FILMIC_ORGANIC",
    type: "light_leak",
    defaultDuration: 0.4,
    defaultEasing: "ease_in_out",
    easingCurve: [0.4, 0, 0.2, 1],
    descriptionSk: "Teplý anamorfický záblesk slnka a filmovej expozície",
    descriptionEn: "Warm vintage optical flare and exposure bloom",
    icon: "✨",
    recommendedSfx: "film_click",
  },
  {
    id: "preset-film-burn",
    nameSk: "Filmový Burn & Šum",
    nameEn: "Film Burn & Sprocket",
    category: "FILMIC_ORGANIC",
    type: "film_burn",
    defaultDuration: 0.35,
    defaultEasing: "linear",
    easingCurve: [0, 0, 1, 1],
    descriptionSk: "35mm analógový prepal filmu a vintage zrnitosť",
    descriptionEn: "35mm analog burn with organic chromatic fringes",
    icon: "🎞️",
    recommendedSfx: "film_click",
  },
  {
    id: "preset-flash-white",
    nameSk: "Impaktný Biely Flash",
    nameEn: "Impact White Flash",
    category: "FILMIC_ORGANIC",
    type: "flash_white",
    defaultDuration: 0.25,
    defaultEasing: "ease_out",
    easingCurve: [0, 0, 0.2, 1],
    descriptionSk: "Krátky energický záblesk svetla na rytmus beatov",
    descriptionEn: "Staccato white flash on hard audio impacts",
    icon: "⚡",
    recommendedSfx: "whoosh",
  },

  // 5. CREATIVE & GLITCH
  {
    id: "preset-glitch",
    nameSk: "Cyber RGB Glitch",
    nameEn: "Cyber RGB Glitch",
    category: "CREATIVE_GLITCH",
    type: "glitch",
    defaultDuration: 0.28,
    defaultEasing: "elastic",
    easingCurve: [0.68, -0.55, 0.265, 1.55],
    descriptionSk: "Digitálny pixel-art posun a chromatická aberácia",
    descriptionEn: "Digital pixel displacement with RGB chromatic split",
    icon: "👾",
    recommendedSfx: "glitch_sfx",
  },
  {
    id: "preset-camera-shake",
    nameSk: "Otras Kamery (Camera Shake)",
    nameEn: "Kinetic Camera Shake",
    category: "CREATIVE_GLITCH",
    type: "camera_shake",
    defaultDuration: 0.3,
    defaultEasing: "spring",
    easingCurve: [0.175, 0.885, 0.32, 1.275],
    descriptionSk: "Dramatický zemetrasný otras a dynamický ráz kamery",
    descriptionEn: "Violent camera earthquake impact jitter with motion blur",
    icon: "📳",
    recommendedSfx: "whip_snap",
  },
  {
    id: "preset-spin-cw",
    nameSk: "Dynamická Rotácia (360° Spin)",
    nameEn: "Whirlpool Spin (360°)",
    category: "CREATIVE_GLITCH",
    type: "spin_cw",
    defaultDuration: 0.38,
    defaultEasing: "cinematic_smooth",
    easingCurve: [0.25, 1, 0.5, 1],
    descriptionSk: "Kinetická 360° rotácia plátna so stredovým ťažiskom",
    descriptionEn: "Centrifugal 360-degree vortex spin transition",
    icon: "🌀",
    recommendedSfx: "whoosh",
  },
  {
    id: "preset-spin-ccw",
    nameSk: "Inverzný Spin (Protismer)",
    nameEn: "Reverse Spin (CCW)",
    category: "CREATIVE_GLITCH",
    type: "spin_ccw",
    defaultDuration: 0.38,
    defaultEasing: "spring",
    easingCurve: [0.16, 1, 0.3, 1],
    descriptionSk: "Rýchla rotácia proti smeru hodinových ručičiek",
    descriptionEn: "Rapid counter-clockwise centrifugal barrel twist",
    icon: "🔄",
    recommendedSfx: "whoosh",
  },
  {
    id: "preset-warp-zoom",
    nameSk: "Hyperspace Warp Zoom",
    nameEn: "Hyperspace Warp Zoom",
    category: "DYNAMIC_ZOOM",
    type: "warp_zoom",
    defaultDuration: 0.32,
    defaultEasing: "cinematic_smooth",
    easingCurve: [0.25, 1, 0.5, 1],
    descriptionSk: "Zakrivenie priestoru a vysokorýchlostná warp akcelerácia",
    descriptionEn: "Dimensional tunnel warping into next scene",
    icon: "🌌",
    recommendedSfx: "whoosh",
  },
  {
    id: "preset-tv-static",
    nameSk: "TV Statický Šum & VHS",
    nameEn: "TV Static & VHS Noise",
    category: "CREATIVE_GLITCH",
    type: "tv_static",
    defaultDuration: 0.26,
    defaultEasing: "linear",
    easingCurve: [0, 0, 1, 1],
    descriptionSk: "Analógový TV šum, prebliknutie kanála a magnetický pruh",
    descriptionEn: "Retro analog TV channel switch with white noise raster",
    icon: "📺",
    recommendedSfx: "glitch_sfx",
  },
  {
    id: "preset-prism-blur",
    nameSk: "Prizmatický Lom & Bokeh",
    nameEn: "Prism Blur & Refraction",
    category: "FILMIC_ORGANIC",
    type: "prism_blur",
    defaultDuration: 0.42,
    defaultEasing: "ease_in_out",
    easingCurve: [0.42, 0, 0.58, 1],
    descriptionSk: "Optický lom svetla cez sklenený hranol s farebným okrajom",
    descriptionEn: "Optical glass refraction with subtle spectral chromatic dispersion",
    icon: "💎",
    recommendedSfx: "film_click",
  },
  {
    id: "preset-split-horizontal",
    nameSk: "Kinematická Závierka",
    nameEn: "Cinematic Split Shutter",
    category: "CREATIVE_GLITCH",
    type: "split_horizontal",
    defaultDuration: 0.32,
    defaultEasing: "spring",
    easingCurve: [0.16, 1, 0.3, 1],
    descriptionSk: "Horizontálne otvorenie nového záberu z dvoch strán",
    descriptionEn: "Horizontal shutter blades parting from frame center",
    icon: "✂️",
    recommendedSfx: "swish",
  },
];

export const EASING_OPTIONS: {
  id: TransitionEasing;
  nameSk: string;
  nameEn: string;
  css: string;
  curve: [number, number, number, number];
  descriptionSk: string;
  descriptionEn: string;
}[] = [
  {
    id: "cinematic_smooth",
    nameSk: "Kinematicky Hladká (Odporúčané)",
    nameEn: "Cinematic Smooth (Recommended)",
    css: "cubic-bezier(0.25, 1, 0.5, 1)",
    curve: [0.25, 1, 0.5, 1],
    descriptionSk: "Prirodzený zrýchľujúci a mäkko dobiehajúci pohyb",
    descriptionEn: "Natural acceleration with silky smooth deceleration",
  },
  {
    id: "spring",
    nameSk: "Pružný Snap (Spring)",
    nameEn: "Spring Snap",
    css: "cubic-bezier(0.175, 0.885, 0.32, 1.275)",
    curve: [0.175, 0.885, 0.32, 1.275],
    descriptionSk: "Dynamický odraz a energetické dosadnutie",
    descriptionEn: "Dynamic overshoot with energetic spring bounce",
  },
  {
    id: "ease_in_out",
    nameSk: "Plynulá (Ease In-Out)",
    nameEn: "Smooth (Ease In-Out)",
    css: "cubic-bezier(0.42, 0, 0.58, 1)",
    curve: [0.42, 0, 0.58, 1],
    descriptionSk: "Symetrický nábeh aj dobeh",
    descriptionEn: "Balanced ramp-in and ramp-out",
  },
  {
    id: "ease_out",
    nameSk: "Rýchly Štart, Mäkký Dojazd (Ease Out)",
    nameEn: "Fast Start, Soft Finish (Ease Out)",
    css: "cubic-bezier(0, 0, 0.2, 1)",
    curve: [0, 0, 0.2, 1],
    descriptionSk: "Okamžitý impulz s pozvoľným spomalením",
    descriptionEn: "Immediate impulse easing softly into place",
  },
  {
    id: "ease_in",
    nameSk: "Pomalý Nábeh (Ease In)",
    nameEn: "Slow Build (Ease In)",
    css: "cubic-bezier(0.4, 0, 1, 1)",
    curve: [0.4, 0, 1, 1],
    descriptionSk: "Postupná akcelerácia na záver",
    descriptionEn: "Gradual build-up towards sudden finish",
  },
  {
    id: "elastic",
    nameSk: "Elastická (Hyper Bounce)",
    nameEn: "Hyper Bounce (Elastic)",
    css: "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
    curve: [0.68, -0.55, 0.265, 1.55],
    descriptionSk: "Výrazný spätný náťah pred prudkým odrazom",
    descriptionEn: "Anticipation pullback followed by bouncy snap",
  },
  {
    id: "linear",
    nameSk: "Lineárna (Rovnomerná)",
    nameEn: "Linear (Constant)",
    css: "linear",
    curve: [0, 0, 1, 1],
    descriptionSk: "Nemenná rýchlosť po celú dobu trvania",
    descriptionEn: "Steady uniform velocity",
  },
];

export const getEasingCss = (easing: TransitionEasing, customCurve?: [number, number, number, number]): string => {
  if (customCurve && customCurve.length === 4) {
    return `cubic-bezier(${customCurve[0]}, ${customCurve[1]}, ${customCurve[2]}, ${customCurve[3]})`;
  }
  const match = EASING_OPTIONS.find((e) => e.id === easing);
  return match ? match.css : "cubic-bezier(0.25, 1, 0.5, 1)";
};
